openapi: 3.0.3
info:
  title: LARPConnect API
  version: 0.0.1
paths:
  /v1/message:
    get:
      operationId: getMessage
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageRequest'
        default:
          description: Default error response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Status'
  /healthz:
    get:
      operationId: healthz
      responses:
        "200":
          description: OK
        "204":
          description: No Content
        "500":
          description: Internal Server Error
  /.well-known/webfinger:
    get:
      operationId: webfinger
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WebfingerResponse'
  /.well-known/nodeinfo:
    get:
      operationId: nodeinfoWellKnown
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NodeinfoJrd'
  /admin/nodeinfo:
    get:
      operationId: nodeinfoAdmin
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Nodeinfo22'
components:
  schemas:
    Nodeinfo22:
      type: object
      properties:
        version:
          type: string
        instance:
          $ref: '#/components/schemas/NodeinfoInstance'
        software:
          $ref: '#/components/schemas/NodeinfoSoftware'
        protocols:
          type: array
          items:
            type: string
        services:
          $ref: '#/components/schemas/NodeinfoServices'
        open_registrations:
          type: boolean
        usage:
          $ref: '#/components/schemas/NodeinfoUsage'
        metadata:
          type: object
          additionalProperties:
            type: string
    NodeinfoInstance:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
    NodeinfoJrd:
      type: object
      properties:
        links:
          type: array
          items:
            $ref: '#/components/schemas/NodeinfoJrdLink'
    NodeinfoJrdLink:
      type: object
      properties:
        rel:
          type: string
        href:
          type: string
    NodeinfoServices:
      type: object
      properties:
        inbound:
          type: array
          items:
            type: string
        outbound:
          type: array
          items:
            type: string
    NodeinfoSoftware:
      type: object
      properties:
        name:
          type: string
        version:
          type: string
        repository:
          type: string
        homepage:
          type: string
    NodeinfoUsage:
      type: object
      properties:
        users:
          $ref: '#/components/schemas/NodeinfoUsageUsers'
        local_posts:
          type: integer
          format: uint32
        local_comments:
          type: integer
          format: uint32
    NodeinfoUsageUsers:
      type: object
      properties:
        total:
          type: integer
          format: uint32
        active_halfyear:
          type: integer
          format: uint32
        active_month:
          type: integer
          format: uint32
        active_week:
          type: integer
          format: uint32
    WebfingerLink:
      type: object
      properties:
        rel:
          type: string
        type:
          type: string
        href:
          type: string
    WebfingerResponse:
      type: object
      properties:
        subject:
          type: string
        aliases:
          type: array
          items:
            type: string
        properties:
          type: object
          additionalProperties:
            type: string
        links:
          type: array
          items:
            $ref: '#/components/schemas/WebfingerLink'
    Authentication:
      type: object
      properties:
        username:
          type: string
        status:
          type: integer
          format: enum
    GoogleProtobufAny:
      type: object
      properties:
        '@type':
          type: string
          description: The type of the serialized message.
      additionalProperties: true
      description: Contains an arbitrary serialized message along with a @type that describes the type of the serialized message.
    Header:
      type: object
      properties:
        accept:
          type: array
          items:
            type: string
    MessageRequest:
      type: object
      properties:
        traceparent:
          $ref: '#/components/schemas/Observability'
        authentication:
          $ref: '#/components/schemas/Authentication'
        header:
          $ref: '#/components/schemas/Header'
        proto:
          $ref: '#/components/schemas/ProtoDef'
        mime:
          $ref: '#/components/schemas/MimeType'
    MimeType:
      type: object
      properties:
        type:
          type: string
        subtype:
          type: string
        content:
          type: string
          format: bytes
    Observability:
      type: object
      properties:
        version:
          type: integer
          format: uint32
        traceId:
          type: string
          format: bytes
        spanId:
          type: string
          format: bytes
        flags:
          type: integer
          format: uint32
    ProtoDef:
      type: object
      properties:
        protobufName:
          type: string
        message:
          $ref: '#/components/schemas/GoogleProtobufAny'
    Status:
      type: object
      properties:
        code:
          type: integer
          description: The status code.
          format: int32
        message:
          type: string
          description: A developer-facing error message.
        details:
          type: array
          items:
            $ref: '#/components/schemas/GoogleProtobufAny'
          description: A list of messages that carry the error details.
