larpconnect {
  blocking-dispatcher {
    type = Dispatcher
    executor = "thread-pool-executor"
    thread-pool-executor {
      core-pool-size-min = 4
      core-pool-size-factor = 2.0
      core-pool-size-max = 32
    }
    throughput = 1
  }

  server {
    host = "0.0.0.0"
    host = ${?LARPCONNECT_SERVER_HOST}
    port = 8080
    port = ${?PORT}
    port = ${?LARPCONNECT_SERVER_PORT}
    name = "default-server"
    name = ${?LARPCONNECT_SERVER_NAME}
    primary-domain = "larpconnect.org"
    primary-domain = ${?LARPCONNECT_SERVER_PRIMARY_DOMAIN}
    admin-contact = "admin@larpconnect.org"
    admin-contact = ${?LARPCONNECT_SERVER_ADMIN_CONTACT}
  }

  data {
    database {
      trust-auth = false
      trust-auth = ${?LARPCONNECT_DATA_DATABASE_TRUST_AUTH}
      migration {
        jdbc-url = "jdbc:postgresql://localhost:5432/larpconnect"
        jdbc-url = ${?LARPCONNECT_DATA_DATABASE_MIGRATION_JDBC_URL}
        username = "njall"
        username = ${?LARPCONNECT_DATA_DATABASE_MIGRATION_USERNAME}
        password = ""
        password = ${?LARPCONNECT_DATA_DATABASE_MIGRATION_PASSWORD}
        trust-auth = ${?LARPCONNECT_DATA_DATABASE_MIGRATION_TRUST_AUTH}
        schemas = ["njall", "njall_admin", "njall_users", "njall_system"]
        default-schema = "njall"
      }
      admin {
        jdbc-url = "jdbc:postgresql://localhost:5432/larpconnect"
        jdbc-url = ${?LARPCONNECT_DATA_DATABASE_ADMIN_JDBC_URL}
        username = "njall_admin"
        username = ${?LARPCONNECT_DATA_DATABASE_ADMIN_USERNAME}
        password = ""
        password = ${?LARPCONNECT_DATA_DATABASE_ADMIN_PASSWORD}
        trust-auth = ${?LARPCONNECT_DATA_DATABASE_ADMIN_TRUST_AUTH}
        pool {
          min-size = 2
          max-size = 10
          timeout-seconds = 5
        }
      }
      users {
        jdbc-url = "jdbc:postgresql://localhost:5432/larpconnect"
        jdbc-url = ${?LARPCONNECT_DATA_DATABASE_USERS_JDBC_URL}
        username = "njall_users"
        username = ${?LARPCONNECT_DATA_DATABASE_USERS_USERNAME}
        password = ""
        password = ${?LARPCONNECT_DATA_DATABASE_USERS_PASSWORD}
        trust-auth = ${?LARPCONNECT_DATA_DATABASE_USERS_TRUST_AUTH}
        pool {
          min-size = 5
          max-size = 20
          timeout-seconds = 5
        }
      }
    }
  }
}
